// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_logging`, `rt`

/// Start the p2panda node. Returns this node's short ID (first 8 chars of public key).
Future<String> startNode() => RustLib.instance.api.crateApiChatStartNode();

/// Send a chat message. Broadcast to all nearby devices via gossip.
Future<void> sendMessage({required String message}) =>
    RustLib.instance.api.crateApiChatSendMessage(message: message);

/// Shut down the node.
Future<void> stopNode() => RustLib.instance.api.crateApiChatStopNode();
